### ISSUE TITLE
新建一个控制台程序 引用surging，网关运行

### ISSUE THREAD

**Issue by wowhoonet** [dotnetcore/surging#101]
![image](https://user-images.githubusercontent.com/28723527/41041075-b4577370-69d0-11e8-9643-7ffe2fba6564.png)
![Uploading image.png…]()

错误信息A suitable constructor for type 'Surging.ApiGateway.Startup' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.”
 请问是什么原因呀

**Comment by fanliang11** [comment]
错误信息已经提示的很清楚了，缺少Startup这个类

**Comment by fanliang11** [comment]
建议你可以晚一点学习surging ，请先巩固下dotnetcore 基础知识
