### ISSUE TITLE
容器化部署服务时，通过网关访问返回服务端通讯时发生了异常 I/O error occurred.

### ISSUE THREAD

**Issue by sd797994** [dotnetcore/surging#102]
服务和网关在本机直接部署没有问题。可以访问。将服务部署到容器之后。
根据之前的帖子配置了 0.0.0.0
![image](https://user-images.githubusercontent.com/26075482/41094463-f9f7cd8e-6a80-11e8-8784-21254e5c1d59.png)
容器也映射了正确的端口
![image](https://user-images.githubusercontent.com/26075482/41094516-1bc20614-6a81-11e8-900d-725e0bb49796.png)
consul能正确获取路由信息
![image](https://user-images.githubusercontent.com/26075482/41094596-61156b16-6a81-11e8-9847-6c962d8ff885.png)

，网关健康检查也能通过
![image](https://user-images.githubusercontent.com/26075482/41094533-2a91a884-6a81-11e8-9599-17d5d5c29558.png)
但是调用网关访问服务时
![image](https://user-images.githubusercontent.com/26075482/41094551-37b65974-6a81-11e8-8e94-f4fe44d1f28a.png)
返回异常
![image](https://user-images.githubusercontent.com/26075482/41094571-45047eda-6a81-11e8-9f86-10c7b1f48d7a.png)

Surging.Core.CPlatform.Exceptions.CommunicationException: 与服务端通讯时发生了异常。 ---> DotNetty.Transport.Channels.ClosedChannelException: I/O error occurred.

**Comment by fanliang11** [comment]
如果你设置了以下特性，需要传递serviceKey=User,如果没有设置就不需要传递
 ```c#
    [ModuleName("User")]
    public class UserService : ProxyServiceBase, IUserService
 ```

**Comment by sd797994** [comment]
增加了serviceKey之后，
![image](https://user-images.githubusercontent.com/26075482/41135326-a4f2a588-6b03-11e8-95f2-3bee4fbfaf8e.png)
从网关断点到RemoteInvokeService.InvokeAsync时，依旧发生了异常
![image](https://user-images.githubusercontent.com/26075482/41094571-45047eda-6a81-11e8-9f86-10c7b1f48d7a.png)

**Comment by fanliang11** [comment]
如果使用我的例子应该请求
 ```c#
{"user":{"UserId":1}}
 ```

**Comment by sd797994** [comment]
![image](https://user-images.githubusercontent.com/26075482/41136141-8364584a-6b07-11e8-817e-c85774b17e49.png)
![image](https://user-images.githubusercontent.com/26075482/41136177-aed9f03e-6b07-11e8-9707-424a8745f29a.png)

**Comment by sd797994** [comment]
就是直接采用的您的sample部署的docker，不过网关我是在宿主机上，但是理论上应该不冲突对吧，毕竟docker映射了外网tcp端口

**Comment by fanliang11** [comment]
如果网关显示正常，应该是连接成功，可能会是以下情况
1.Codec 不统一，造成反序列化错误
2. 是否同一版本，是不是最新版本0.7.0.1

**Comment by sd797994** [comment]
完全从新克隆了surging，网关F5运行抛异常了
![image](https://user-images.githubusercontent.com/26075482/41138593-e8997e36-6b14-11e8-8466-b55627433c1d.png)

**Comment by fanliang11** [comment]
最新版本
https://github.com/dotnetcore/surging/commit/f86eaa603f26aa29b4abb4ea4fe24c033d5964ff
建议你还是仔细看看，为了不影响其它人，暂且关闭，如果还有其它问题，请开启。
