### ISSUE TITLE
怎么在服务端获取HttpHeaders参数，比如当前登录用户Id

### ISSUE THREAD

**Issue by jakcm** [dotnetcore/surging#138]
1.通过JWT在Headers中传入Authorization Token，怎么在服务端获取当前登录用户Id？
调试楼主源码调用服务时_authorizationServerProvider.GetPayloadString(author)，网关这里是有用户Id的，怎么在服务中获取用户Id？
2.以及其他HttpHeaders中的数据，比较客户端IP，通过RpcContext.GetContext()获取到的数据是空的。
3.在HttpHeaders中传入多语言语种，服务端怎么获取？

**Comment by fanliang11** [comment]
1.第一个问题：
传递的模型需继承RequestData，RequestData代码如下
```c#
public class RequestData 
    {
        public string Payload { get; set; }
    }
```
比如传递的是IdentityUser，IdentityUser代码如下
```c#
    public class IdentityUser:RequestData
    {
        public string RoleId { get; set; }
    }
```
读取基类的Payload 属性
2.第二问题暂时不支持读取客户端IP

**Comment by jakcm** [comment]
@fanliang11 
感谢楼主及时回复，我在版本0.6.5 May 1 2018试了，继承RequestData后Payload是空的，源码中_typeConvertibleService.Convert(value, parameterType)这段代码转换后Payload就是空了。
是不是版本不够新？

**Comment by fanliang11** [comment]
刚刚测试是OK，0.6.5也没问题，还是多检查自己的代码吧

**Comment by jakcm** [comment]
知道原因了，是继承RequestData的类上面标注了Serializable，去掉就可以了。多谢
