### ISSUE TITLE
服务JWT验证通过后获取token的payload报错

### ISSUE THREAD

**Issue by wlhappy01** [dotnetcore/surging#160]
作者你好，
按照之前的issue的方法测试你的demo中的 public Task<IdentityUser> Save(IdentityUser requestData)方法，试图获取payload，但是经过JWT验证后调用Save(IdentityUser requestData)方法报错，错误信息为
Surging.Core.DotNetty.DotNettyTransportClientFactory[0]
Surging.Core.CPlatform.Exceptions.CommunicationException: 与服务端通讯时发生了异常。 ---> System.TypeLoadException: GenericArguments[0], 'Newtonsoft.Json.Linq.JContainer', on 'MessagePack.Formatters.NonGenericListFormatter`1[T]' violates the constraint of type parameter 'T'.

调试发现是
![image](https://user-images.githubusercontent.com/586103/45138491-2ddbc100-b1df-11e8-80c1-0886a1deb196.png)
序列化内容为{"{\"UserId\":22,\"Name\":\"admin\",\"Age\":0}"}
报错

![image](https://user-images.githubusercontent.com/586103/45138523-4b108f80-b1df-11e8-891e-329bdc4bb488.png)

**Comment by fanliang11** [comment]
1.可以通过RpcContext.GetContext().GetAttachment("payload") 和继承RequestData 获取payload
