### ISSUE TITLE
redis缓存问题

### ISSUE THREAD

**Issue by binliang11** [dotnetcore/surging#163]
![qq 20180909040028](https://user-images.githubusercontent.com/38573430/45258138-4fa69500-b3e5-11e8-855f-9a0a240a8641.png)
![qq 20180909040100](https://user-images.githubusercontent.com/38573430/45258139-50d7c200-b3e5-11e8-807c-f7e84e330573.png)
使用缓存的过程中，第一次获取到数据添加到redis，然后我传入不同的参数值想获取不同的数据但是返回的总是第一次获取的数据

**Comment by binliang11** [comment]
![image](https://user-images.githubusercontent.com/38573430/45264790-ba52e180-b474-11e8-8b9a-7326f1429ab8.png)
![image](https://user-images.githubusercontent.com/38573430/45264794-d35b9280-b474-11e8-9aa8-edac10bc04ad.png)
调试源码发现Key是空的

**Comment by binliang11** [comment]
![image](https://user-images.githubusercontent.com/38573430/45264965-3b12dd00-b477-11e8-9d5b-e8f1ca9af9b0.png)
调试源码发现Key是空的

**Comment by binliang11** [comment]
![image](https://user-images.githubusercontent.com/38573430/45265033-44507980-b478-11e8-8674-c048bbdf7833.png)
调试源码发现Key并没有赋值

**Comment by fanliang11** [comment]
经过查看没有问题一切正常
![default](https://user-images.githubusercontent.com/17928535/45265115-2df6ed80-b479-11e8-96d6-aaee905b099e.png)
![default](https://user-images.githubusercontent.com/17928535/45265081-cb055680-b478-11e8-99d7-4f19bfca6f64.png)
![default](https://user-images.githubusercontent.com/17928535/45265139-6991b780-b479-11e8-8588-dbb2e03df2bd.png)

**Comment by binliang11** [comment]
![image](https://user-images.githubusercontent.com/38573430/45265182-f472b200-b479-11e8-90d0-b6416b0f67eb.png)
嗯    调试发现是我没有指定key赋值     谢谢
