### ISSUE TITLE
[Exception Occured] Same service.server with port changed met exception while registering

### ISSUE THREAD

**Issue by grammyleung** [dotnetcore/surging#169]
同一套Surging.Services.Server代码配置文件surgingSetting.json里的"Surging" / "Port" 值改成了其他值，再次启动出错，从显示内容来看是删除原来的旧的节点信息的时候找不到对象。

![qq 20181006012249](https://user-images.githubusercontent.com/1329782/46550390-80f08300-c907-11e8-821b-9c39ec4e0ee8.jpg)
![qq 20181006012414](https://user-images.githubusercontent.com/1329782/46550401-88179100-c907-11e8-893a-72ac11147b2a.jpg)

曾经做过的非常规操作是在consul 8500管理界面里手动清空了key/value值。

**Comment by fanliang11** [comment]
这个是缓存注册中心，缓存注册中心之前没有考虑多个实例ID合并操作，所以你要保证多个服务节点是统一个配置文件， 服务注册中心没有这个问题。

**Comment by fanliang11** [comment]
已经修改了算法，现在每台独立的服务可以配置独立的缓存配置。

**Comment by grammyleung** [comment]
It's just exactly what I want. 谢谢群主，么么哒！
