### ISSUE TITLE
[Exception Ocurred] private variable _routes was null in class ConsulServiceRouteManager

### ISSUE THREAD

**Issue by grammyleung** [dotnetcore/surging#171]
{System.ArgumentNullException: Value cannot be null. Parameter name: source    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)    at Surging.Core.Consul.ConsulServiceRouteManager.ChildrenChange(String[] oldChildrens, String[] newChildrens) in C:\src\SurgingApiGateway\Surging.Core\Surging.Core.Consul\ConsulServiceRouteManager.cs:line 318    at Surging.Core.Consul.ConsulServiceRouteManager.<EnterRoutes>b__22_0(String[] oldChildrens, String[] newChildrens) in C:\src\SurgingApiGateway\Surging.Core\Surging.Core.Consul\ConsulServiceRouteManager.cs:line 225} | System.ArgumentNullException

![qq 20181009032318](https://user-images.githubusercontent.com/1329782/46629239-c1076e00-cb72-11e8-9133-090f45dabe91.jpg)

操作非常正常而且干净，重启了电脑，然后刚启动了Gateway，然后再启动Services.Server，最后PostMan了一个服务，共计三个操作。就遇到了这个问题。

**Comment by grammyleung** [comment]
异常发生时，Consul中的keyValue在重启后还保持了之前的所有服务信息。

**Comment by fanliang11** [comment]
首先gateway先启动，会从注册中心获取serviceroutes,后启动service.server虽然会更新注册中心serviceroutes,但是这个时候访问gateway读取的是本地缓存的serviceroutes,要过一段时间等心跳更新了本地缓存才能正常访问

**Comment by grammyleung** [comment]
额外追问一个问题，干净安装的默认状态下，Services.Server的配置文件更新了IP或者端口之后，多长时间才会更新到Consul里，Consul更新后，Gateway多长时间会更新到本地缓存里？谢谢！

**Comment by fanliang11** [comment]
server 启动后就会更新consul,  默认在2分钟内serviceroutes更新至本地
