### ISSUE TITLE
[Exception Occurred] SocketException in ConfigureRoute of ServiceHostBuilderExtensions.cs

### ISSUE THREAD

**Issue by grammyleung** [dotnetcore/surging#173]
一切正常地运行Gateway和Server，试过通过Gateway调用服务返回都没问题，就放着没动，网关和服务都开着大概有十分钟干别的去了。跑服务的那个突然间就弹出了异常，如图。（这个异常是发生在跑服务的Project里的，网关Project没有发生异常。）

![qq 20181010233937](https://user-images.githubusercontent.com/1329782/46748647-99d1ad80-cce6-11e8-90f8-8efc6259a929.jpg)

异常文字内容如下：
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Surging.Core.CPlatform.ServiceHostBuilderExtensions.<>c__DisplayClass4_0.<ConfigureRoute>b__0() in C:\Users\...\src\SurgingServices\Surging.Core\Surging.Core.CPlatform\ServiceHostBuilderExtensions.cs:line 143
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

Inner Exception 1:
HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

Inner Exception 2:
SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

请问这种情况会是哪一方的连接出了问题？因为我的工作场景是：在虚拟机里跑服务器通过虚拟网卡的路由器桥接来获取虚拟服务器的局域网IP，虚拟服务器里运行consul、rabbitMQ和redis，再在开发机器上跑网关和服务来调用虚拟服务器，我担心是不是路由器不稳定，让服务和consul之间的通讯不够连续，被他捕获了刹那间的没有应答？

如果是这样的话，有没有必要handle这个异常？要不然服务就奔溃重启了。

**Comment by grammyleung** [comment]
当我按了continue继续调试的时候，RabbitMQ貌似出问题了。但是我此时此刻telnet vm-ip:5672 是通的。

![qq 20181011001431](https://user-images.githubusercontent.com/1329782/46750516-bec81f80-ccea-11e8-926a-a8c35e0f004c.jpg)

**Comment by fanliang11** [comment]
现在注册中心宕机也不会造成引擎的任何影响，可以照常运行访问调用。第二个问题是RabbitMQ.client抛出的，无法判定。还是自己调试分析。

**Comment by grammyleung** [comment]
可以确定第二个问题也是宕机造成的，因为我把注册中心和RabbitMQ放在同一个服务器上了。后来我已经人为制造了宕机，出现了同样的情况。您看看有没有必要把这个RabbitMQ.Client也handle一下？

**Comment by fanliang11** [comment]
你可以使用release试运行，看下注册中心和rabbitmq宕机，会不会造成服务引擎的崩溃无法运行，rabbitmq崩溃会造成消费者订阅失效，但是不影响内部调用，这个问题会在下版本修复，

**Comment by grammyleung** [comment]
好，我先pull，再在新版本的基础上找机会试试rabbit。
