### ISSUE TITLE
[Exception Occurred] [Question] Gateway Policy on Registered Address Modification

### ISSUE THREAD

**Issue by grammyleung** [dotnetcore/surging#177]
场景：
1、正常运行Gateway（IP:GatewayAddress）+Services.Server（IP:ServiceAddress1）。
1.1、访问 http://ServiceAddress1:[port]/[path] 可正常获取返回值
1.2、访问 http://GatewayAddress:[port]/[path] 可正常获取返回值
2. 用后将Services.Server服务器IP改变成ServiceAddress2。
2.1、访问 http://ServiceAddress2:[port]/[path] 可正常获取返回值
2.2、访问 http://GatewayAddress:[port]/[path] 引发异常，消费者需要长期等待直到超时出错。

异常初步分析：Gateway中的DotNetty依然希望访问ServiceAddress1并获取返回值。

局部检查：
1. Consul中的KeyValue值中已经在原有的ServiceAddress1后加入了ServiceAddress2。
2. Gateway的服务管理中能看到新旧1和2两个地址同时存在，1异常2正常。

希望了解的问题：
1. 是否应该从熔断注入等角度才能解决这个问题？
2. 默认配置情况下，ServiceAddress2需要多长时间才能在Gateway里替换掉ServiceAddress1?
3. 不知道是否是健康检查的结果，系统已经可以获知1异常2正常这个情况了，如何能让2立刻代替1进行工作？

谢谢！

以下是部分关键截图：
![qq 20181016134814](https://user-images.githubusercontent.com/1329782/46996432-2f3dc900-d14f-11e8-8406-36819293859d.jpg)
![qq 20181016134723](https://user-images.githubusercontent.com/1329782/46996434-306ef600-d14f-11e8-8ffa-ae712ea9c13d.jpg)
![qq 20181016134701](https://user-images.githubusercontent.com/1329782/46996442-37960400-d14f-11e8-9ddf-b1ae5a9b192d.jpg)

**Comment by fanliang11** [comment]
1.有健康检查，服务检查不健康超过超过6次，会从注册中心移除。
2. 如果针对服务还没进行健康检查，就访问不健康的服务，会发生错误，会根据规则进行容错，然后标识这个服务为不健康的，如果选择的是故障转移策略会重新选择健康的服务。
3.心跳更新本地的serviceroutes，大概2分钟内会更新本地的serviceroutes

**Comment by grammyleung** [comment]
好的，故障转移策略我再仔细研究一下。不过想追问上述案例中的异常是否会导致网关运行异常？生产环境中部署网关的时候，是否要就把网关服务设置成失败重启即可，以避免未知的异常？

**Comment by fanliang11** [comment]
不需要重启网关的，看业务场景，如果数据比较重要，可以设置故障转移策略

**Comment by grammyleung** [comment]
看到了，用Try包着的。我一直以为Try里面的异常在VS调试中不会产生中断。
