### ISSUE TITLE
[Exception Occurred] Unknow ddlCache Setting 127.0.0.1:7005

### ISSUE THREAD

**Issue by grammyleung** [dotnetcore/surging#191]
场景描述：调用网关路径测试JWT鉴权调用GetUserId的时候，在OAuth里面的AuthorizationServerProvider.cs中ValidateClientAuthentication里_cacheProvider.GetAsync<string>触发了RedisCache过程中的异常。

POSTMAN Address: http://localhost:729/api/User/GetUserId?userName=Jackson
POSTMAN Authorization: Bearer xxxx.....xxxxx

异常主要内容：我在ApiGate和Services.Server下的cacheSetting.json中都没有显示提到127.0.0.1:7005这个地址和端口，但是不知为何系统会自己去掉用它？因为这个地址不存在，导致Redis调用异常。

相关截图 ——

异常断点截图：
![default](https://user-images.githubusercontent.com/1329782/47620289-7babe000-db23-11e8-9e0e-60ceca7c31b4.png)

网关里的cacheSetting关键部位：
![qq 20181029023828](https://user-images.githubusercontent.com/1329782/47620314-bf064e80-db23-11e8-85bf-7377a4fa4787.jpg)

服务里的cacheSetting关键部位：
![qq 20181029023926](https://user-images.githubusercontent.com/1329782/47620326-dfcea400-db23-11e8-995f-c9e86d61fbf0.jpg)

**Comment by fanliang11** [comment]
-请查看其它引擎的同一实例id下缓存是否配置了7005端口，缓存配置会注册到注册中心，再通过心跳更新到网关和服务提供者

**Comment by grammyleung** [comment]
看到了，注册中心里面有ddlCache和userCache的配置，就是源码里带的。里面有以上配置文件中双斜杠注释掉的内容，7000和7005都有，7005排到了第一位。将要验证清空注册中心重启实例后是否还有同样情况。

**Comment by grammyleung** [comment]
【追问】如果接口定义了FailOver策略，该策略是否也适用于类似本案例缓存多地址的切换？

**Comment by grammyleung** [comment]
经过测试，完全删除双斜杠部分的内容，不再有7000/7005注册到注册中心去了。

我崩溃了，泪奔了，万马奔腾中！悲痛地关闭Issue！
