### ISSUE TITLE
网关调用服务超时。

### ISSUE THREAD

**Issue by JimmyPoor** [dotnetcore/surging#196]
调试网关调用服务功能时发现网关访问服务一直超时，但是按照例子，Console 服务和客户端没有问题
有点奇怪是配置问题么
服务代码

`  [ServiceBundle("api/{Service}")]
    public interface IDemoService : IServiceKey
    {
        [Service(Date = "2018-11-10")]
        Task<Dictionary<string, object>> GetAllThings();
    }

    [ModuleName("Demo")]
    public class DemoService :ProxyServiceBase, IDemoService
    {
        public DemoService()
        {

        }

       
        public async Task<Dictionary<string, object>> GetAllThings()
        {
            return await Task.FromResult(new Dictionary<string, object> { { "aaa",12} });
        }
    }`
![default](https://user-images.githubusercontent.com/10822432/48309219-18549000-e5b0-11e8-8fd6-3f7534946227.PNG)
![2](https://user-images.githubusercontent.com/10822432/48309232-420db700-e5b0-11e8-902f-3d5711bdcbb5.PNG)

**Comment by fanliang11** [comment]
我先看看，稍后答复你，是否是BUG

**Comment by fanliang11** [comment]
![default](https://user-images.githubusercontent.com/17928535/48379984-03434280-e711-11e8-8437-da4b828b6f9b.png)
没有任何问题
