### ISSUE TITLE
值为NULL的问题

### ISSUE THREAD

**Issue by qiuyoo** [dotnetcore/surging#204]
Surging.Core.CPlatform.Exceptions.CPlatformCommunicationException: Value cannot be null.
如果是返回值是NULL 会报错，如果传NULL到服务也会报错，有什么办法可以解决。

**Comment by jfwangncs** [comment]
问下你这个怎么解决？

**Comment by qiuyoo** [comment]
弄一个返回的类，把实体或者 参数都放进去。
