### ISSUE TITLE
Surging.Core.CPlatform.Exceptions.CommunicationException: 与服务端通讯时发生了异常。 ---> DotNetty.Transport.Channels.NotYetConnectedException: I/O error occurred.

### ISSUE THREAD

**Issue by jfwangncs** [dotnetcore/surging#220]
最新版的代码，网关显示正常
![1](https://user-images.githubusercontent.com/27275625/50473986-1f1d5200-09fa-11e9-8b85-c0a428bfa7a7.jpg)

![image](https://user-images.githubusercontent.com/27275625/50474004-365c3f80-09fa-11e9-866c-25de17f2f82a.png)

![image](https://user-images.githubusercontent.com/27275625/50473995-2ba1aa80-09fa-11e9-8e6a-c79db75e8450.png)

通过Postman post的时候 提示Surging.Core.CPlatform.Exceptions.CommunicationException: 与服务端通讯时发生了异常。 ---> DotNetty.Transport.Channels.NotYetConnectedException: I/O error occurred.
![image](https://user-images.githubusercontent.com/27275625/50474045-5ee43980-09fa-11e9-8f06-40661ea5afc3.png)
![image](https://user-images.githubusercontent.com/27275625/50474061-6dcaec00-09fa-11e9-8014-f08faff33aef.png)

**Comment by jfwangncs** [comment]
出现了 The requested service 'Employee (AccountMircoServer.IModuleServices.IEmployeeService)' has not been registered
，是什么情况啊。翻遍了issue有个一个说开了MQ，我这边是用最近的代码，没有开MQ。
![image](https://user-images.githubusercontent.com/27275625/50501230-820df800-0a91-11e9-91de-f9fe41ad11ac.png)

**Comment by fanliang11** [comment]
上面已经说的很清楚了，你的服务提供者IEmployeeService 接口没有依赖注入，请自己检查代码
