### ISSUE TITLE
返回模型循环引用

### ISSUE THREAD

**Issue by jfwangncs** [dotnetcore/surging#221]
用的EF Core。Model 定义大概是
`public class Employee
    {     
        [DisplayName("角色")]
        public List<RoleEe> RoleEe { get; set; }
    }
 [Table("Role")]
     public class RoleEe
    {
        public int RoleId { get; set; }
        public Role Role { get; set; }
        public int EeId { get; set; }
        public Employee Employee { get; set; }
    }
`
当我调Employee返回值用了include，在MessagePack 序列化的时候就会直接退出进程。
![image](https://user-images.githubusercontent.com/27275625/50511045-f31bd280-0ac6-11e9-8151-c9f5c1213ecb.png)

这个问题怎么办啊？如果我查询的时候不include，后面怎么能得到RoleEe的数据？

**Comment by fanliang11** [comment]
添加  [IgnoreMember]忽略掉Employee 这个属性

**Comment by jfwangncs** [comment]
需要引用那个类？没找到

**Comment by jfwangncs** [comment]
是IgnoreDataMember这个？

**Comment by fanliang11** [comment]
需要引用messagepack,而messagepack 只能是忽略掉这个属性，如果你觉得这个方案不可行通过routepath 进行访问，以下是代码
```c#
ServiceLocator.GetService<IServiceProxyProvider>();
            Dictionary<string, object> model = new Dictionary<string, object>();
            model.Add("user", JsonConvert.SerializeObject(new
            {
                Name = "fanly",
                Age = 18,
                UserId = 1
            },new JsonSerializerSettings() { ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore  }));
 serviceProxyProvider.Invoke<object>(model, path, serviceKey);
    ```
还是建议不要使用循环引用，性能损耗非常严重，请斟酌

**Comment by jfwangncs** [comment]
查了些资料，messagepack是不支持循环引用的。那想问下我用的EF Core有导航属性，就会产生类似循环引用，如果我去掉这些导航属性，获取所有数据会变的更复杂。我如果不用EF Core有什么推荐吗？

**Comment by fanliang11** [comment]
感觉应该是你的设计有问题，所有的序列化都不支持，你自己考虑下吧，分成两次来查询
