### ISSUE TITLE
返回值为null

### ISSUE THREAD

**Issue by jfwangncs** [dotnetcore/surging#223]
方法定义
![image](https://user-images.githubusercontent.com/27275625/50535023-ff179b00-0b7f-11e9-9ba8-4a00e3256b95.png)
调用到时候 如果返回为null
会出现
![image](https://user-images.githubusercontent.com/27275625/50535046-3f771900-0b80-11e9-8e5f-4705e69e5e32.png)

**Comment by fanliang11** [comment]
一开始考虑是返回Task<ApiResult<T>>,现在已经可以支持返回null了
