### ISSUE TITLE
1.0版本生成代理对象报错

### ISSUE THREAD

**Issue by binliang11** [dotnetcore/surging#228]
![qq 20190103040520](https://user-images.githubusercontent.com/38573430/50610140-d8a18900-0f0c-11e9-9711-e2e34234213b.png)
![qq 20190103040525](https://user-images.githubusercontent.com/38573430/50610146-dc351000-0f0c-11e9-9614-01b7b5df85e0.png)

**Comment by fanliang11** [comment]
请参考apigateway
