### ISSUE TITLE
服务加入网关后可以通过http方式给app调用吗？给app调用的地址是怎么组合的呢。

### ISSUE THREAD

**Issue by qingask** [dotnetcore/surging#23]
场景：有2个一样的服务，加入网关，对外以http方式提供给app调用，给app调用的这个url是怎么组合的呢？网关host+model id+方法名吗？

**Comment by fanliang11** [comment]
需要添加[ServiceBundle("api/{Service}")]配置服务路由规则，以便生成routepath，通过routepath去定位查服务路由

**Comment by qingask** [comment]
还不是很清楚这个routepath最终生成的url是什么，假如网关的部署地址是 http://127.0.0.1:729，api/{Service}的Service名是user，方法是getuser，生成最终的可以让app进行htpp调用的routepath是什么呢？

**Comment by fanliang11** [comment]
routhpath 生成的是 api/user/getuser,  应该通过 http://127.0.0.1:729/api/user/getuser地址访问，如果配置了[ModuleName("User")]，还需要加？serviceKey=User

**Comment by qingask** [comment]
试了一下，consul和surging服务,apigateway三个均启动了，但以http的方式get和post访问工程自带的示例user，都没有访问成功，没有任何信息返回也没报错，访问地址是： http://localhost:729/api/user/GetUserName?serviceKey=User&id=11  是哪里没操作不对吗？

**Comment by fanliang11** [comment]
如果有参数的话，就需要在放到body里post 提交，选择application/json
应该是提交{id:11}

**Comment by fanliang11** [comment]
如果有参数的话，就需要把内容放到body里post 提交，选择application/json
如果你访问GetUserName的话？应该提交{“id”:11}

**Comment by qingask** [comment]
好的，谢谢，我再试下。

**Comment by chenzhikang** [comment]
在AttributeServiceEntryProvider类的GetEntries下的entries.AddRange( _clrServiceEntryFactory.CreateServiceEntry(service));这一行打断点，看下entries里面对应的服务的地址是什么，就可以访问了。

**Comment by chenzhikang** [comment]
http服务访问的格式：http://localhost:729/api/userlevel/getcurrentservicename?serviceKey=UserLevel
	a) 服务定义类：UserLevelService  及[ModuleName("UserLevel")]
	b) 服务定义接口：IUserLevelService  及[ServiceBundle("api/{Service}")]；
	c) 注意：Service大小写问题。
