### ISSUE TITLE
关于DotNetty异步编程的疑问

### ISSUE THREAD

**Issue by inversionhourglass** [dotnetcore/surging#230]
最近在找.NET比较好的底层通讯框架时研究了一下DotNetty，然后我发现DotNetty并不直接支持异步编程，`ChannelHandlerAdapter.ChannelRead`是void返回值，虽然在DotNetty的[issue](https://github.com/Azure/DotNetty/issues/265)中找到一条回复说可以直接改成async void，但尝试发现会发生死锁。我看你的代码实现中是直接包一层Task.Run实现，这表示你也认为DotNetty不直接支持异步编程吗？
https://github.com/dotnetcore/surging/blob/188e341cc2396b59bb786d4e0be91b6efaa84967/src/Surging.Core/Surging.Core.DotNetty/DotNettyServerMessageListener.cs#L147-L154

此前我们一直使用Thrift作为RCP框架，但在突然的高并发下经常出现超时的现象，排查后定位再Thrift的.NET实现将请求ThreadPool交由处理，在突然的大并发下，ThreadPool短时间并发任务排队会使某些任务排队很长时间才能够分配到线程。而Task内部默认使用[ThreadPool](https://github.com/dotnet/coreclr/blob/dc3f080b89b7d3c85afdb8b6d2b9086363c48c14/src/System.Private.CoreLib/shared/System/Threading/Tasks/ThreadPoolTaskScheduler.cs#L44)实现。DotNetty固定创建几个线程，使用EventLoop的方式处理请求，但现在就在异步编程这里卡住了，如果有什么看法，还望指教。

**Comment by fanliang11** [comment]
ChannelRead是编解码，如果长时间同步处理会阻塞dotnetty线程，所以这里交由ThreadPool处理

**Comment by inversionhourglass** [comment]
你应该只看了我节选的代码片段，没有看具体问题
