### ISSUE TITLE
请问使用Surging MQTT协议做离线消息推送是否可行？

### ISSUE THREAD

**Issue by wlhappy01** [dotnetcore/surging#231]
请问使用Surging MQTT协议做离线消息推送是否可行？

**Comment by fanliang11** [comment]
可以通过网关publish willmessage,里面需要的WillRetain的是保留遗嘱消息（也就是订阅相关的topic,发送相关的离线消息），QOS=0 是 清除基于topic 的遗嘱消息，QOS>0是保留以前的遗嘱消息，并且添加到遗嘱消息列表中，然后设备订阅topic后，会send 遗嘱消息，具体操作看下图
![default](https://user-images.githubusercontent.com/17928535/50678865-b6f2ef80-103b-11e9-817d-1010a0780dce.png)

**Comment by wlhappy01** [comment]
感谢！
1.首先测试发现Qos仅仅能设置为0，设置为1或2则返回
{
    "IsSucceed": false,
    "Message": "Exception of type 'DotNetty.Codecs.EncoderException' was thrown.|InnerException:Object reference not set to an instance of an object.",
    "StatusCode": 400
}

2.其次，如果Client处于连接状态是可以收到的；但在WillRetain=true的情况下，客户端离线后发布Topic信息，客户端再次连接还是不能接受到离线之前的消息
{"deviceId":"",

"message":{
"Topic":"/T",
"Message":"fff",
"Qos":0,
"WillRetain":true
}
}
3.使用MQnetclient客户端测试，将发布消息的retain设置为true，发布消息Surging服务端出错
public MqttApplicationMessage(string topic, byte[] payload, MqttQualityOfServiceLevel qualityOfServiceLevel, **bool retain**);
var appMsg = new MqttApplicationMessage(topic, Encoding.UTF8.GetBytes(inputString), MqttQualityOfServiceLevel.AtMostOnce, true);
![image](https://user-images.githubusercontent.com/586103/50680238-eefd3100-1041-11e9-98dc-46f6739ebd26.png)
![image](https://user-images.githubusercontent.com/586103/50680259-ffada700-1041-11e9-8a9f-0d0e1057ba74.png)
![image](https://user-images.githubusercontent.com/586103/50680272-0b996900-1042-11e9-83da-3c7c7381015b.png)

以上，辛苦了~！感谢

**Comment by fanliang11** [comment]
WillRetain=True 可以收到你再试试，Qos>0报错我再看看

**Comment by wlhappy01** [comment]
> WillRetain=True 可以收到你再试试，Qos>0报错我再看看

我测试还是不能收到离线消息，不知是不是我的流程不对
我的流程是
1.先连接发送一次消息
![image](https://user-images.githubusercontent.com/586103/50719485-7cd72b80-10d7-11e9-9897-2557f49d772a.png)
2.退出客户端，再发送一条消息
![image](https://user-images.githubusercontent.com/586103/50719491-a1cb9e80-10d7-11e9-9918-78d6ab8a7300.png)
3.再用同样的userid和topic连接进来，看是否收到消息，结果未收到
![image](https://user-images.githubusercontent.com/586103/50719505-f0793880-10d7-11e9-998a-0c88f818573c.png)

**Comment by fanliang11** [comment]
![aw4c9ak9fap6lafh uoorwi](https://user-images.githubusercontent.com/17928535/50719685-2c61cd00-10db-11e9-9741-c9d064c44a30.png)
![g32pz6y 9 8 2 4 64 b h](https://user-images.githubusercontent.com/17928535/50719687-2f5cbd80-10db-11e9-8a37-1e9949fc3a60.png)
为了不影响他人，你的issues 会进行close ，你的其它的问题，会进行检查，谢谢！
