### ISSUE TITLE
存储在redis缓存的token与请求Headers中携带的token相差一个Bearer

### ISSUE THREAD

**Issue by Gisder** [dotnetcore/surging#234]
范大哥您好！您开源的Surging框架很厉害，最近一直在学习中。
在测试Task<int> GetUserId(string userName)这个接口的时候总是提示“Invalid authentication credentials”。在调试过程中发现下面这个函数验证总是不通过。
![image](https://user-images.githubusercontent.com/8625718/50684908-2e337e00-1052-11e9-86d4-16f6009c8983.png)
发现_cacheProvider.GetAsync<string>(jwtToken[1])从redis中取到的token是“eyJUeXBlIjowLCJFbmNyeXB0TW9kZSI6MCwiVGltZVN0YW1wIjoiMjAxOS0wMS0wNCAwNjozMToyMyJ9.IntcIlVzZXJJZFwiOjIyLFwiTmFtZVwiOlwiYWRtaW5cIixcIkFnZVwiOjB9Ig==.oig+y719wbLKS3xUl4Ed4S+uLMgyo9AdKrGDcNrbhD4=” 
而请求Header中携带的token是“Bearer eyJUeXBlIjowLCJFbmNyeXB0TW9kZSI6MCwiVGltZVN0YW1wIjoiMjAxOS0wMS0wNCAwNjozMToyMyJ9.IntcIlVzZXJJZFwiOjIyLFwiTmFtZVwiOlwiYWRtaW5cIixcIkFnZVwiOjB9Ig==.oig+y719wbLKS3xUl4Ed4S+uLMgyo9AdKrGDcNrbhD4=”
两者相差一个“Bearer”，导致验证总是不通过。
请问是我哪里参数配置不对吗？

**Comment by fanliang11** [comment]
在Headers  中添加Authorization，Headers 明白吗？

**Comment by Gisder** [comment]
> 在Headers 中添加Authorization，Headers 明白吗？

OK，问题已解决！
