### ISSUE TITLE
服务调用

### ISSUE THREAD

**Issue by hyihao** [dotnetcore/surging#24]
serviceProxyProvider.Invoke<object>(model, path, serviceKey);
我写了一个测试 在service.client
   public static void Test(IServiceProxyProvider serviceProxyProvider)
        {
            Dictionary<string, object> model = new Dictionary<string, object>();
            model.Add("UserId", "1");
            string path = "api/user/getuser";
            string serviceKey = "User";

            var userProxy = serviceProxyProvider.Invoke<object>(model, path, serviceKey);
            var s = userProxy.Result;
        }
想通过api 方式调用服务
服务端和客户端启动后
![image](https://user-images.githubusercontent.com/1115391/34097351-d947f210-e413-11e7-98e5-b2a441c721b0.png)
user返回的信息
![image](https://user-images.githubusercontent.com/1115391/34097372-eb4b1e24-e413-11e7-8b61-f0d769d60431.png)
返回的是自定义属性当中的？
![image](https://user-images.githubusercontent.com/1115391/34097422-0deb34f0-e414-11e7-9f8d-9e7e579b5f27.png)

**Comment by fanliang11** [comment]
已经注册了，请在网关修改

**Comment by hyihao** [comment]
拉取最新代码？

**Comment by fanliang11** [comment]
你用这个方法试试
 public static void TestForRoutePath(IServiceProxyProvider serviceProxyProvider)
        {
            Dictionary<string, object> model = new Dictionary<string, object>();
            model.Add("user",  new
            {
                Name = "fanly",
                Age = 18,
                UserId = 1
            });
            string path = "api/user/getuser";
            string serviceKey = "User";

            var userProxy = serviceProxyProvider.Invoke<object>(model, path, serviceKey);
            var s = userProxy.Result;
            Console.WriteLine("Press any key to exit...");
            Console.ReadLine();
        }

**Comment by fanliang11** [comment]
```c#
 public static void TestForRoutePath(IServiceProxyProvider serviceProxyProvider)
        {
            Dictionary<string, object> model = new Dictionary<string, object>();
            model.Add("user",  new
            {
                Name = "fanly",
                Age = 18,
                UserId = 1
            });
            string path = "api/user/getuser";
            string serviceKey = "User";

            var userProxy = serviceProxyProvider.Invoke<object>(model, path, serviceKey);
            var s = userProxy.Result;
            Console.WriteLine("Press any key to exit...");
            Console.ReadLine();
        }
```

**Comment by SkipperGuo** [comment]
在客户端调用服务端的时候  发生错误给定的密钥不在字典当中不知是什么意思，服务端提示消息发送失败。 @fanliang11 
![image](https://user-images.githubusercontent.com/14214355/34664158-7d975e46-f495-11e7-8ce3-1d94ff9c7660.png)

**Comment by SkipperGuo** [comment]
Dictionary<string, object> model = new Dictionary<string, object>
            {
                {
                    "audit", JsonConvert.SerializeObject(new
                    {
                        UserName = "simple",
                        Action = "testaction",
                        MentodName = "test",
                        MethodParams = "params",
                        OperatorIp = "127.0.0.1"
                    })
                }
            };
           
            string path = "api/audit/insertAuditAsync";
            string serviceKey = "Audit";
            var userProxy = serviceProxyProvider.Invoke<object>(model, path, serviceKey); 调用方法是这样

**Comment by fanliang11** [comment]
不需要再JsonConvert.SerializeObject

**Comment by fanliang11** [comment]
serviceProxyProvider.Invoke<object>(model, path, serviceKey);
不推荐使用，因为不支持缓存拦截

**Comment by SkipperGuo** [comment]
不是这样的，在源码的demo中JsonConvert.SerializeObject 有这个也是可以调用成功，nuget上下载的，有没有JsonConvert.SerializeObject  都会报出这样的错误

**Comment by SkipperGuo** [comment]
因为不想去引用服务的dll，所以用serviceProxyProvider.Invoke(model, path, serviceKey)这种方式

**Comment by fanliang11** [comment]
贴下你的方法参数

**Comment by fanliang11** [comment]
ModuleName 设置的什么

**Comment by SkipperGuo** [comment]
![image](https://user-images.githubusercontent.com/14214355/34664740-3957e98c-f498-11e7-977b-0f737b6d8cb1.png)
![image](https://user-images.githubusercontent.com/14214355/34664748-44aab4c2-f498-11e7-96b1-e2424939a634.png)
每一个参数都是必须传的吗？

**Comment by SkipperGuo** [comment]
ModuleName 设置的是Audit

**Comment by fanliang11** [comment]
insertAuditAsync方法呢？

**Comment by SkipperGuo** [comment]
![image](https://user-images.githubusercontent.com/14214355/34664806-8b6a9a6c-f498-11e7-9392-5c38fc2d3119.png)
接口的方法是这样定义的

**Comment by fanliang11** [comment]
Dictionary<string, object> model = new Dictionary<string, object>
{
{
"entity", new
{
UserName = "simple",
Action = "testaction",
MentodName = "test",
MethodParams = "params",
OperatorIp = "127.0.0.1"
}
}
};
        string path = "api/audit/insertAuditAsync";
        string serviceKey = "Audit";
        var userProxy = serviceProxyProvider.Invoke<object>(model, path, serviceKey);  试试

**Comment by SkipperGuo** [comment]
![image](https://user-images.githubusercontent.com/14214355/34664893-08fdea1a-f499-11e7-8e61-c6091a420cc3.png)
这种我yij已经试过了。不行的

**Comment by fanliang11** [comment]
```c#
Dictionary<string, object> model = new Dictionary<string, object>
{
{
"entity", new
{
UserName = "simple",
Action = "testaction",
MentodName = "test",
MethodParams = "params",
OperatorIp = "127.0.0.1"
}
}
};
string path = "api/audit/insertAuditAsync";
string serviceKey = "Audit";
var userProxy = serviceProxyProvider.Invoke(model, path, serviceKey); 
```
试试

**Comment by SkipperGuo** [comment]
ok，调用成功，感谢作者。这里实体的时候  字典的键 都必须是entity？

**Comment by fanliang11** [comment]
记得点个赞

**Comment by SkipperGuo** [comment]
嗯呐，测试完了之后，会写个博客把踩了的坑  都写出来，大家一起学习。
