### ISSUE TITLE
无法获取缓存信息时抛出异常

### ISSUE THREAD

**Issue by Oceania2018** [dotnetcore/surging#245]
`_consul.KV.Keys(_configInfo.CachePath)` throw exception when cache path not found.
![image](https://user-images.githubusercontent.com/1705364/51155536-6e0e1880-183d-11e9-942d-bbee30e3ab6d.png)

**Comment by fanliang11** [comment]
经查没有此问题

**Comment by Oceania2018** [comment]
截图为证，我会Pull Request.

**Comment by Oceania2018** [comment]
![image](https://user-images.githubusercontent.com/1705364/51155900-d0b3e400-183e-11e9-81e2-9a11f2196665.png)

**Comment by Oceania2018** [comment]
Close Consul agent could reproduce this issue.
