### ISSUE TITLE
Mqtt服务调用其他服务创建客户端时Bootstrap.handler 无法返回值

### ISSUE THREAD

**Issue by yifonewang** [dotnetcore/surging#248]
### A客户端配置代码：
` Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            var host = new ServiceHostBuilder()
                .RegisterServices(builder =>
                {
                    builder.AddMicroService(option =>
                    {
                        option.AddServiceRuntime()
                        .AddCache()
                            .AddRelateService()
                            .AddConfigurationWatch();
                        builder.Register(p => new CPlatformContainer(ServiceLocator.Current));
                    });
                })
                .ConfigureLogging(logger =>
                {
                    logger.AddConfiguration(
                        AppConfig.GetSection("Logging"));
                })
                .UseNLog(LogLevel.Debug, "NLog.config")
                .UseServer(options => { })
                .UseConsoleLifetime()
                .Configure(build =>
                    build.AddCacheFile("${cachepath}|cacheSettings.json", optional: false, reloadOnChange: true))
                .Configure(build =>
                    build.AddCPlatformFile("${surgingpath}|surgingSettings.json", optional: false, reloadOnChange: true))
                    .UseLockerMongoDb()
                .UseStartup<Startup>()
                .Build();

            using (host.Run())
            {
                Console.WriteLine($"服务端启动成功，{DateTime.Now}。");
            }`
### B服务端代码：
`Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            var host = new ServiceHostBuilder()
                .RegisterServices(builder =>
                {
                    builder.AddMicroService(option =>
                    {
                        option
                        .AddServiceRuntime()
                            .AddCache()
                            .AddRelateService()
                            .AddConfigurationWatch()
                            .UseMessagePackCodec();
                        builder.Register(p => new CPlatformContainer(ServiceLocator.Current));
                    });
                })
                .ConfigureLogging(logger =>
                {
                    logger.AddConfiguration(
                        AppConfig.GetSection("Logging"));
                })
                .UseNLog(LogLevel.Debug, "NLog.config")
                .UseServer(options => { })
                .UseProxy()
                .UseConsoleLifetime()
                .Configure(build =>
                    build.AddCacheFile("${cachepath}|cacheSettings.json", optional: false, reloadOnChange: true))
                .Configure(build =>
                    build.AddCPlatformFile("${surgingpath}|surgingSettings.json", optional: false, reloadOnChange: true))
                .UseStartup<Startup>()
                .Build();

            using (host.Run())
            {
                Console.WriteLine($"服务端启动成功，{DateTime.Now}。");
            }`
### C客户端代码：
`Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            var host = new ServiceHostBuilder()
                .RegisterServices(builder =>
                {
                    builder.AddMicroService(option =>
                    {
                        option.AddClient()
                        .AddCache();
                        builder.Register(p => new CPlatformContainer(ServiceLocator.Current));
                    });
                })
                .ConfigureLogging(logger =>
                {
                    logger.AddConfiguration(
                        AppConfig.GetSection("Logging"));
                })
                .Configure(build =>
                build.AddEventBusFile("eventBusSettings.json", optional: false))
                .Configure(build =>
                build.AddCacheFile("cacheSettings.json", optional: false, reloadOnChange: true))
                .Configure(build =>
                build.AddCPlatformFile("${surgingpath}|surgingSettings.json", optional: false, reloadOnChange: true))
                .UseClient()
                .UseStartup<Startup>()
                .Build();

            using (host.Run())
            {
                Startup.Test(ServiceLocator.GetService<IServiceProxyFactory>());
            }`
### 当C调用A服务代码：
`var userProxy = serviceProxyFactory.CreateProxy<ILockersRepositoryService>();
var e = await userProxy.InsertLockerAsync(locker);`
**在客户端C调用A时可以成功并返回结果。**
### 当B调用A服务代码：
`_lockersRepository = serviceProxyFactory.CreateProxy<ILockersRepositoryService>();await _lockersRepository.InsertLockerAsync(locker);`
**在服务端B调用A时创建客户端时没有报错但客户端**
![image](https://user-images.githubusercontent.com/44156687/51361046-26231600-1b09-11e9-855c-5e34d8ee6710.png)
### 但无返回，对应_bootstrap.Handler生成的pipeline如下
![image](https://user-images.githubusercontent.com/44156687/51361094-5cf92c00-1b09-11e9-90d0-2125f1a9f9a7.png)
![image](https://user-images.githubusercontent.com/44156687/51361114-75694680-1b09-11e9-807e-c60928f3f8fd.png)
**请问是配置的问题么？如果是请问下少什么配置信息 谢谢**

**Comment by fanliang11** [comment]
首先不要用serviceProxyFactory.CreateProxy<ILockersRepositoryService>()，基类都帮你封装好了，this.GetService(), 还有你贴这个我是分析不出来的，我只能猜测，你的服务注册有问题，导致netty 连接失败，请通过http://127.0.0.1:8500/ui 你看下key/value 的注册信息

**Comment by yifonewang** [comment]
首先我用的是MQTT的Service端继承自基类MqttBehavior，因此调用this.GetService()，必须要把实现这个接口的类也需要引用进来，因此我目前用的是serviceProxyFactory.CreateProxy();
其次如图所示需要调用服务的IP为
![image](https://user-images.githubusercontent.com/44156687/51365028-4bb81b80-1b19-11e9-9dd0-29a83916e4b6.png)
调用的服务Ip为
![image](https://user-images.githubusercontent.com/44156687/51365046-61c5dc00-1b19-11e9-9524-c00b973059bb.png)
