### ISSUE TITLE
如果某个服务的实例由熔断从服务路由集合中被移除,那么还会被重新添加到路由集合中吗?

### ISSUE THREAD

**Issue by liuhll** [dotnetcore/surging#256]
如题，如果某个服务的实力请求失败，服务不健康导致服务的路由从路由集合中移除，那么还可能会重新添加到路由集合中吗？如果会的话，多久会尝试重新注册?

**Comment by fanliang11** [comment]
不会重新注册，报错不要移除，只会通过socket去检查网络，如果失败6次会进行移除，所以请确保网络的稳定。

**Comment by liuhll** [comment]
我会经常遇到这样的事情,在服务注册中心的`serviceCommands`看到服务实力的相关元数据,但是在`serviceRoutes`下却看不到相关的元数据,这个是由于网络异常导致的该问题么？

**Comment by liuhll** [comment]
不是不信任，是向您请教，有的代码还是不太好理解！没有觉得不好什么的
