### ISSUE TITLE
项目运行cpu100%

### ISSUE THREAD

**Issue by Andy-Yin** [dotnetcore/surging#257]
![tim 20190127163942](https://user-images.githubusercontent.com/8369493/51798721-38f8c180-2252-11e9-82b9-0c44a9bb57eb.png)
复现步骤：
1. clone最新代码，开始redis，mq，consul（全win10环境，本机127.0.0.1）。
2. 只启动网关，debug模式运行一个多小时后，cpu100%。

分析进程提示：dotnet.exe一个或者多个进程处于等待状态

**Comment by Andy-Yin** [comment]
非必现，后续我看下能否复现

**Comment by fanliang11** [comment]
自己检查下，如果不做任何逻辑调用，apigateway只会从注册中心心跳更新

**Comment by Andy-Yin** [comment]
好的。
