### ISSUE TITLE
启动报错：Autofac.Core.Registration.ComponentNotRegisteredException

### ISSUE THREAD

**Issue by leoterry-ulrica** [dotnetcore/surging#259]
服务启动时候，抛出以下异常：
Autofac.Core.Registration.ComponentNotRegisteredException:“The requested service 'Surging.Core.CPlatform.Support.IServiceCommandManager' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.”

是配置出问题了吗？谢谢

**Comment by fanliang11** [comment]
没有引用注册中心引擎组件，consul 或者zookeeper ，请检查你的代码

**Comment by leoterry-ulrica** [comment]
okay  谢谢
