### ISSUE TITLE
api网关调用rpc服务时，如果参数不符，直接返回了Entity:null，机制有问题；

### ISSUE THREAD

**Issue by chenzhikang** [dotnetcore/surging#26]
问题描述：
方法定义：public Task<UserLevelModel> GetUserLevelModel(string userid)

此时如果http post的请求中，没有传递参数，目前机制是直接返回结果：{"Entity":null,"IsSucceed":true,"Message":"","StatusCode":200}
resp结果中没有参数不正确的提示；

且：此时用户的代码压根没执行，因此用户程序中参数为空的检查是不执行的。

原因分析：经过断点跟踪，
在 public async Task<ServiceResult<object>> Path(string path, [FromQuery]string serviceKey, [FromBody]Dictionary<string, object> model)   的model参数为null或者参数的key不在model中，在发起rpc调用时TransportClient类 SendAsync方法，会抛异常，api网关直接将返回如上结果。

结论：此处的判断逻辑或者说错误提示应该更加明确，在参数不齐全的情况下，异常后的排查成本会很高。

**Comment by fanliang11** [comment]
这是一个问题，周末打算是整理下网关的异常处理机制

**Comment by fanliang11** [comment]
这是一个问题，这个版本会整理下网关的异常处理机制，
