### ISSUE TITLE
在数据库修改数据后需要重启服务才能获取到更新后的数据。

### ISSUE THREAD

**Issue by NaturalDragon** [dotnetcore/surging#261]
Fanly先生您好，现在遇到这个问题，在数据库修改数据后，不管在swagger中调试api或通过网关调用api获取到的数据都是之前的值，重启服务后调用api能获取到更新更改后的数据。
api也没有开启缓存。
         [Authorization(AuthType = AuthorizationType.JWT)]
        Task<PageData> GetPageList(GoodsoPageRequestDto goodsoPageRequestDto);

**Comment by fanliang11** [comment]
那是你数据访问的问题，和引擎无关

**Comment by NaturalDragon** [comment]
我在webapi中用相同的数据访问代码是能够实时获取最新数据的
