### ISSUE TITLE
Surging.Core.CPlatform中的ClrServiceEntryFactory类

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/surging#268]
这个类的能修改成控制下autofac的生命周期吗。发现业务模块下面的的类都是单例的模式.
![default](https://user-images.githubusercontent.com/20178645/54026245-29b54e00-41d8-11e9-9c94-aa50d159ac2c.png)

**Comment by xueandfeng** [comment]
因为之前类都是通过autofac进行注入控制类的生命周期的。现在单例的模式会有问题。
所以是希望业务模块的类能通过autofac控制生命周期

**Comment by fanliang11** [comment]
性能会超级慢超级慢，建议还是单例

**Comment by fanliang11** [comment]
注：IsModulePerLifetimeScope 开启性能不好，慎用，请使用单例

**Comment by xueandfeng** [comment]
好的，谢谢老大

**Comment by xueandfeng** [comment]
老大。https://github.com/dotnetcore/surging/blob/40fe9ababb5d08ec39d3cfb46f9a48d24a09ab8d/src/Surging.Core/Surging.Core.CPlatform/Runtime/Server/Implementation/ServiceDiscovery/Implementation/ClrServiceEntryFactory.cs#L92
这个地方只是当前类进行autofac控制了生命周期。但是构造方法注入的类还是单例的。
