### ISSUE TITLE
拦截器功能里面能否新增设置参数或者修改参数值?

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/surging#275]
在客户端远程代理的时候。
我想在全局进行一个参数或者多个参数进行传递传递到服务端.

**Comment by fanliang11** [comment]
缓存降级吗？请看这个
https://github.com/dotnetcore/surging/issues/153

**Comment by xueandfeng** [comment]
不是缓存降级。我是自定义拦截器的。就是想单纯的在拦截器里面进行全局的一个参数添加到这个字典里面传递到服务端
![图片](https://user-images.githubusercontent.com/20178645/55220793-07e14100-5243-11e9-9730-53603e49dc09.png)

**Comment by fanliang11** [comment]
你可以用隐性传参的方式，在拦截器中添加以下代码
```c#
RpcContext.GetContext().SetAttachment("name","value"); 
```
在服务端使用以下代码获取
```c#
RpcContext.GetContext().GetAttachment("name"); 
```

**Comment by xueandfeng** [comment]
好的，谢谢
