### ISSUE TITLE
求助，内存和句柄数持续上涨

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/surging#285]
![图片](https://user-images.githubusercontent.com/20178645/56552701-a94b8080-65be-11e9-9434-24c88448396e.png)
1860是surging.services.client客户端的pid
13232是surging.service.service服务端的pid
下载源码进行跑一遍后。什么都不干。观察几分钟后
![图片](https://user-images.githubusercontent.com/20178645/56552860-224ad800-65bf-11e9-93b1-65c97ddedf2d.png)
发现这个一直上涨。

**Comment by fanliang11** [comment]
因为预热生成代理了，你调用了内存就下去了

**Comment by xueandfeng** [comment]
不是啊。我就这样干挂着个程序。一天下来我内存快1G了。句柄数4w多了

**Comment by xueandfeng** [comment]
客户端程序就是正常的。服务端的程序就是我上面说的情况

**Comment by fanliang11** [comment]
造成这种问题情况，应该是你的机器配置不行，或者你是用IDE运行项目，执行上万次访问，造成netty 的worker 线程阻塞，导致内存升高，句柄上升，要不你就发布release后运行. 我的机器运行了1个星期没关都没有问题。双核，四核，六核都测试过，或者你可以用dump分析下。

**Comment by MetSystem** [comment]
先dump看看是不是netty 占用的

**Comment by xueandfeng** [comment]
![图片](https://user-images.githubusercontent.com/20178645/56845668-411ad880-68f7-11e9-8260-d6e8134bd43b.png)
看着是dotnetty的。我的是在win下挂着跑的的。服务端开启程序。客户端开一个每秒访问一个接口。一天下来内存就上去了

**Comment by MetSystem** [comment]
试试加上这个
Environment.SetEnvironmentVariable("io.netty.allocator.numDirectArenas", "0");

**Comment by MetSystem** [comment]
看看这个
https://www.cnblogs.com/shuxiaolong/p/DotNetty_OutOfMemory.html

**Comment by xueandfeng** [comment]
这个今天上午加上了，开着程序再跑，明天看效果

**Comment by fanliang11** [comment]
为什么我的程序不会，很稳定

**Comment by xueandfeng** [comment]
不清楚啊，我的也是github下载的。一般是要跑一晚上时间，第二天一看内存和句柄数就很高了。我的是在win下的

**Comment by fanliang11** [comment]
我跑了一星期不间断1万次没发现这种情况

**Comment by xueandfeng** [comment]
最新的，还是1.0的，我的是github最新的

**Comment by fanliang11** [comment]
最新的，你找找你的问题吧

**Comment by xueandfeng** [comment]
@fanliang11  我这边还是一样的之前问题。
![图片](https://user-images.githubusercontent.com/20178645/57602404-93aff200-7591-11e9-8b5e-fa2be85c0b8e.png)
![图片](https://user-images.githubusercontent.com/20178645/57602464-be9a4600-7591-11e9-86cc-66335c5c3c8d.png)
句柄数量20分钟左右涨到现在这么多了。
![图片](https://user-images.githubusercontent.com/20178645/57602537-f3a69880-7591-11e9-810c-94f24e2a0517.png)

![图片](https://user-images.githubusercontent.com/20178645/57602578-133dc100-7592-11e9-8035-c682689a2c60.png)

**Comment by xueandfeng** [comment]
[surging-master-test.zip](https://github.com/dotnetcore/surging/files/3171613/surging-master-test.zip)
上面是测试的源码 
![image](https://user-images.githubusercontent.com/20178645/57603965-8f85d380-7595-11e9-90c8-7014c0761400.png)
![image](https://user-images.githubusercontent.com/20178645/57604009-adebcf00-7595-11e9-9d4f-81ec41c86604.png)
我测试的源码差异就是上面标注的

**Comment by fanliang11** [comment]
不要用IDE，不要用IDE, 不要用IDE, 重要的事情说三遍，请不要再发了，打扰别人
