### ISSUE TITLE
RpcContext获取Payload问题

### ISSUE THREAD

**Issue by ggh5270** [dotnetcore/surging#288]
token通过 RpcContext.GetContext().SetAttachment("payload", payload)这方式传给接口，当网关部署多个节点时，使用 RpcContext.GetContext().GetAttachment("payload")获取回token，会出现token获取错乱的问题。请问楼主是否有这个问题？

**Comment by fanliang11** [comment]
什么错乱问题，请描述清楚

**Comment by ggh5270** [comment]
部署多个网关节点的情况下，A和B两个用户登陆，当B用户调用接口时，有可能会获取到了A的token。原因分析是：网关传token给接口，用的是固定的payload这个key，接口获取token也是用payload这个key，导致取了其它人的token，请问楼主是否有这个问题？

**Comment by fanliang11** [comment]
明确告诉你不会，建议你去看看ThreadLocal

**Comment by liuhll** [comment]
关于获取运行时用户你可以参考的修改的[ClrServiceEntryFactory](https://github.com/liuhll/Surging.Sample/blob/3239098c47af5639aa12decc6e8aa609be1afdb2/src/Core/Surging.Core.CPlatform/Runtime/Server/Implementation/ServiceDiscovery/Implementation/ClrServiceEntryFactory.cs#L121)和这里[Session](https://github.com/liuhll/Surging.Sample/tree/master/src/Core/Surging.Core.CPlatform/Runtime/Session),会相对容易很多

**Comment by ggh5270** [comment]
我们实际的项目中就出现这个问题了，两个用户操作的间隔很短时，就有可能出现，但这种机率非常低，我看了ThreadLocal，有可能是ThreadLocal中的值上次没清空，这个值就会保留下来继续被使用

**Comment by fanliang11** [comment]
ThreadLocal 是线程级变量，而RpcContext 是ThreadLocal 是存储数据的上下文，不同的请求是不同的线程，之间是线程隔离的，你说机率低出现问题，我觉得不可能

**Comment by ggh5270** [comment]
ThreadLocal 的存储数据上下文，不同的请求是不同的线程，之间是线程隔离的
这仲针对单台服务是对的，如果部署多台服务器，这种线程处理就会有问题了，不同服务器线程不一样，导致取的payload就有问题

**Comment by liuhll** [comment]
payload在不同服务之间的传递不是通过rpcParams传递的么?

**Comment by liuhll** [comment]
你可以像我这样处理,在接受到请求的时候:
```csharp
 if (parameters.ContainsKey("payload"))
                     {
                         if (RpcContext.GetContext().GetAttachment("payload") == null)
                         {
                             var serializer = ServiceLocator.GetService<ISerializer<string>>();
                             var payloadString = serializer.Serialize(parameters["payload"], true);
                             RpcContext.GetContext().SetAttachment("payload", payloadString);
                         }
                     }
```
