### ISSUE TITLE
请作者看一下内存现象

### ISSUE THREAD

**Issue by vancechan** [dotnetcore/surging#306]
首先感谢楼主的微服务框架，已在我们的项目中开始使用。
但是目前遇到一个内存问题，想请假一下楼主。

下面是我发现的一个现象：
测试1：我把框架源码中Surging.Services.Server项目单独部署到一台虚拟机上，只部署这一个项目，放置两个小时，内存一直在增加，从44MB，上涨到了52MB，可见下图。
测试2：我把框架源码中Surging.Services.Server项目单独部署到一台物理机上，只部署这一个项目，放置1个小时，内存从刚启动的44MB，下降到了14MB。

真实项目中，由于承载了更多服务，所以内存通常在1G+，

![sc_vm_2_5](https://user-images.githubusercontent.com/19280258/59329418-66399e00-8d21-11e9-972a-1a9328bc3541.PNG)
<img width="579" alt="本地server内存" src="https://user-images.githubusercontent.com/19280258/59329467-849f9980-8d21-11e9-8424-cbb4356e6b66.PNG">
<img width="587" alt="本地server内存2" src="https://user-images.githubusercontent.com/19280258/59329495-984b0000-8d21-11e9-8f38-c869b4915a47.PNG">

**Comment by fanliang11** [comment]
请麻烦生成 DMP 文件进行分析，把跟踪信息贴上来，以上信息很难做出回答

**Comment by vancechan** [comment]
参考下图。
<img width="788" alt="compare" src="https://user-images.githubusercontent.com/19280258/59332026-ebc04c80-8d27-11e9-8d8b-bfa50a48cb5e.PNG">

**Comment by vancechan** [comment]
或者直接下载dump文件
链接：https://pan.baidu.com/s/1fIX1rar5Rf0-Jtf1DJ-m0g 
提取码：f78f

**Comment by vancechan** [comment]
刚刚物理机上的内存只有3MB左右了。
<img width="534" alt="67C64B82-6A0F-456c-AB08-4DDA3904ADCA" src="https://user-images.githubusercontent.com/19280258/59332303-7d2fbe80-8d28-11e9-8951-f2077ff7c565.png">

**Comment by vancechan** [comment]
提问提的这么详细，竟然没有解决办法？

**Comment by fanliang11** [comment]
请自己通过dump分析问题，其它人使用一切正常，如果还有其它问题可以重新提交issues

**Comment by vancechan** [comment]
1.我使用的是你的源代码，没有加任何一行我自己的代码。
2.我是把Surging.Services.Server项目部署到一台**虚拟机**上，出现的内存增加。但是物理机上是减少的。

ps：虚拟机指的是使用vm软件等虚拟出来的pc，比如阿里云，腾讯云的主机。物理机就是传统意义上的pc，没有安装vm的机器。

现在想问的是，在虚拟机和物理机中使用surging，为啥内存会有如此反差呢？
