### ISSUE TITLE
服务健康检查“异常”

### ISSUE THREAD

**Issue by Andy-Yin** [dotnetcore/surging#309]
环境：开发机器（192.168.23.1）+虚拟机（192.168.23.135）
网关：192.168.23.1：729，为了方便debug，本机运行，正常。
consul：192.168.23.135：8500，运行正常。
服务A：192.168.23.1:98，运行正常，注册正常，网关管理页面正常，postman调用正常
服务B：192.168.23.1:99，运行正常，注册正常，网关管理页面显示“异常”，postman不通

尝试方法
1. 本机debug网关，定位到Surging.Core\Surging.Core.CPlatform\Runtime\Client\HealthChecks\Implementation\DefaultHealthCheckService.cs的check监控的方法上，提示“由于目标计算机积极拒绝，无法连接。 192.168.23.1:99”
2. 各种重启大法都试了，无用。包括网关，consul，服务
3. 把服务b的代码删了个干净，只留下了一个task.fromResult()，无效。。
4. 把服务a的配置文件复制到服务b上，只保留端口，也没有作用
5. 防火墙，杀毒软件等各种关闭，无效。。

折腾了半天了，希望
1. 作者给下意见，到底可能那个地方出问题了？
2. 希望框架能给与更多的错误提示，如果一直不健康的话，应该给与服务b的命令行错误提示等。

**Comment by fanliang11** [comment]
还需要给什么提示？已经告诉你了由于目标计算机积极拒绝，无法连接。 192.168.23.1:99,请检查网络环境，用Telnet查看是否连接正常，如果不懂网络知识，可以请专业人员进行部署
