### ISSUE TITLE
Memory Leak, ConsoleLifetime block finalize queue!

### ISSUE THREAD

**Issue by a407121393** [dotnetcore/surging#320]
After application runed, the ConsoleLifetime registered AppDomain.CurrentDomain.ProcessExit event handler will be trigger.
`AppDomain.CurrentDomain.ProcessExit += (sender, eventArgs) =>
            {
                ApplicationLifetime.StopApplication();
                **_shutdownBlock.WaitOne();**
            };`

**Above the codes will be running and block on the finalize thread**, so all another objects would can not be disposed.

The windbg screen shot:
0:002> !Threads
ThreadCount:      200
UnstartedThread:  0
BackgroundThread: 200
PendingThread:    0
DeadThread:       0
Hosted Runtime:   no
                                                                                                        Lock  
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   0    1 c5b78 000001b0d0567520  2022220 Preemptive  0000000000000000:0000000000000000 000001b0d0776f70 0     MTA 
   **2    2 c5b9c 000001b0d056bb50  2023220 Preemptive  0000000000000000:0000000000000000 000001b0d0776f70 0     MTA (Finalizer)** 
   3    3 c5ba4 000001b0d0696920  102a220 Preemptive  0000000000000000:0000000000000000 000001b0d0776f70 0     MTA (Threadpool Worker) 
XXXX    4 c5bb0 000001b0d064c5a0 88039220 Preemptive  0000000000000000:0000000000000000 000001b0d0776f70 0     Ukn (Threadpool Completion Port) 

**0:002> ~~[c5b9c]s**
ntdll!NtWaitForMultipleObjects+0x14:
00007ffc`52400994 c3              ret
**0:002> !clrstack**
OS Thread Id: 0xc5b9c (2)
        Child SP               IP Call Site
00000069720ff5d8 00007ffc52400994 [HelperMethodFrame_1OBJ: 00000069720ff5d8] System.Threading.WaitHandle.WaitOneNative(System.Runtime.InteropServices.SafeHandle, UInt32, Boolean, Boolean)
00000069720ff6f0 00007ffc3d2a024b System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean) [E:\A\_work\307\s\src\mscorlib\src\System\Threading\WaitHandle.cs @ 199]
00000069720ff720 00007ffbdf23c970 **Surging.Core.ServiceHosting.Internal.Implementation.ConsoleLifetime.b__2_1(System.Object, System.EventArgs)**
00000069720ff8c8 00007ffc3d91a673 [GCFrame: 00000069720ff8c8] 
00000069720ff948 00007ffc3d91a673 [GCFrame: 00000069720ff948]

**Comment by fanliang11** [comment]
Code was added last June, there is no problem running, my code referenced here
https://github.com/aspnet/Extensions/blob/0bc7c9f8b5df46e23f255272ba267ad789385a32/src/Hosting/Hosting/src/Internal/ConsoleLifetime.cs
