### ISSUE TITLE
讨论：关于消息队列与网关

### ISSUE THREAD

**Issue by fawdlstty** [dotnetcore/surging#335]
1，也许可以尝试使用ZeroMQ，可以少安装一个中间件
2，网关设计成一个模块，在用户希望用到的地方灵活启用；比如基于kestrel或通过HttpListener直接监听HTTP链接的原始方式上使用网关；另外比如将可视化网关界面移动到某个文件夹下

**Comment by fanliang11** [comment]
1.ZeroMQ会进行考虑，但是可能会延后，因为2.0将会研发引擎探针，做链路跟踪，可以支持组件扩展探针，这样调用会形成一条链路，每一步都会产生跟踪信息
2.stage 已经代替了网关，可视化网关界面还没有计划移植
