### ISSUE TITLE
整体更新新版代码后，EventBusRabbitMQ组件内部报错

### ISSUE THREAD

**Issue by LuceLuo** [dotnetcore/surging#336]
![TIM截图20190726141521](https://user-images.githubusercontent.com/8308243/61930363-143a9800-afb0-11e9-877f-393be634a3bb.png)

**Comment by fanliang11** [comment]
你自己的问题，应该是rabbitmq重复加载了两次

**Comment by LuceLuo** [comment]
没做任何改动，后面重新启动了几次，居然没出错了，神奇了
