### ISSUE TITLE
请问缓存Redis多节点的配置方式是怎么配置？

### ISSUE THREAD

**Issue by wlhappy01** [dotnetcore/surging#340]
比如192.168.1.1 192.168.1.2

   "Maps": [
            {
              "Name": "Redis",
              "Properties": [
                
                {
                  "Name": null,
                  "Ref": null,
                  "Value": "192.168.1.1:6379::1",
                  "Maps": null
                },
                {
                  "Name": null,
                  "Ref": null,
                  "Value": "192.168.1.2:6379::1",
                  "Maps": null
                }
              ]
            }
			]

是这样吗？感谢

**Comment by fanliang11** [comment]
是的。

**Comment by wlhappy01** [comment]
谢谢！
