### ISSUE TITLE
DotNetty 与服务器：127.0.0.1:56476通信时发送了错误

### ISSUE THREAD

**Issue by zhujinhu21** [dotnetcore/surging#342]
错误日志：
Surging.Core.DotNetty.DotNettyServerMessageListener [(null)] - 与服务器：127.0.0.1:56476通信时发送了错误。 DotNetty.Transport.Channels.ChannelException: Exception of type 'DotNetty.Transport.Channels.ChannelException' was thrown. ---> DotNetty.Transport.Libuv.Native.OperationException: ECONNRESET (ECONNRESET) : connection reset by peer    --- End of inner exception stack trace ---

**Comment by fanliang11** [comment]
这个错误是由服务提供者强制关闭连接导致，你需要提供更多信息。
