### ISSUE TITLE
Stage关卡组件 访问服务身份验证的routhpah无法获取payload

### ISSUE THREAD

**Issue by gongap** [dotnetcore/surging#343]
![stage](https://user-images.githubusercontent.com/4032558/62480641-edb40280-b7e2-11e9-9ac5-8fe596a03c2b.gif)
通过ApiGateWay可以正常返回Token
难道是【 聚合服务、中转服务没有服务治理，服务注册与发现】，不能通过routepath访问？
是要将 访问服务身份验证的routhpah另外启动一个服务注册到Consul中？

**Comment by fanliang11** [comment]
可以通过routhepath访问，GetLocalRouteByPathRegex方法就能获取本地的服务。但是概念一定要分清楚，聚合服务和中转服务不是业务逻辑处理的微服务，它只是针对于微服务数据的聚合和中转，无需注册到注册中心，而鉴权服务属于业务逻辑处理的微服务，需要注册到注册中心，所以加载了stage 关卡组件是不能注册中心的，需要移除stage 关卡组件。

**Comment by gongap** [comment]
@fanliang11 明白了，谢谢

**Comment by zhupeng0929** [comment]
那按照上面说的，处理业务的微服务就不能使用stage组件了，那是不是还是得用gateway？这种情况时暂时得吗，后面能够完全使用stage吗？

**Comment by fanliang11** [comment]
加载stage 关卡组件后，其服务变为中间服务、聚合服务，其服务信息不会注册到注册中心，微服务是处理业务逻辑，而中间服务、聚合服务是针对数据进行聚合或者中间化处理，不牵涉从仓储获取、更新数据， RpcContext 在rest 环境下不支持，已经扩展了RestContext 进行隐形传参。如果感兴趣，可以购买企业版
