### ISSUE TITLE
使用consul作为服务注册中心,同时启动多个服务，路由信息可能导致注册失败

### ISSUE THREAD

**Issue by liuhll** [dotnetcore/surging#348]
使用docker-compose编排服务,通过`docker-compose up -d`同时启动多个服务的时候,会存在某个服务实例的路由信息注册失败的情况,但是并非必现的,如果是一个一个的启动服务的话,就不会存在该问题。

**Comment by fanliang11** [comment]
我这边测试没问题，如果你的服务过多，你可以修改LockDelay 锁定过期时间，默认十分钟

**Comment by liuhll** [comment]
嗯  好的 谢谢 我试试看
