### ISSUE TITLE
appsecret 開放給第三方？

### ISSUE THREAD

**Issue by wlhappy01** [dotnetcore/surging#351]
請教appsecret 開放給第三方，第三方給Authorization及timeStamp，如何給？如何獲取Service Token
![image](https://user-images.githubusercontent.com/586103/63141548-b29ea400-c018-11e9-9238-1b07a6fe2871.png)
![image](https://user-images.githubusercontent.com/586103/63141582-e083e880-c018-11e9-8369-2602fc1fc65a.png)

**Comment by fanliang11** [comment]
Service Token是通过配置文件进行设置的，设置“true”代表自动生成令牌，也可以设置具体令牌密钥，鉴权 jwt 和appsecret 都依赖于Token，通过token 可以隔离不同类型的业务服务、聚合服务、中转服务，如何给？你可以当面给，私下给，从数据库拉取给，打电话给，微信给。

**Comment by wlhappy01** [comment]
請問如何獲取ServiceDescriptor？
