### ISSUE TITLE
关于serviceRoutes里AddressDescriptors的健康检查

### ISSUE THREAD

**Issue by LuceLuo** [dotnetcore/surging#361]
没有弄清楚这部分的健康检查是如何处理的，因为使用的是k8s部署，所以主机ip是一直在变的。如果直接把主机ip作为AddressDescriptors就需要能做健康检查，自动更新健康主机才行。现在发现很多失效的主机ip还是存在在Consul里面并没有自动删除。代码里还是认为这部分主机是健康的，以下是我找到的一段代码，所以我要如何解决这个问题，以保证主机的健康。
![TIM截图20190827132238](https://user-images.githubusercontent.com/8308243/63757359-81618600-c8ec-11e9-9ec1-708d34c40ea9.png)

这段代码里面好像没有做健康检查，直接返回了true

**Comment by fanliang11** [comment]
不懂你的意思，请自己研究

**Comment by LuceLuo** [comment]
不懂什么意思，就是这里的服务发现不稳定，离线的服务根本无法识别，直接返回是健康的，什么意思，你说什么意思
