### ISSUE TITLE
surging跑二周内存到6G

### ISSUE THREAD

**Issue by victor596** [dotnetcore/surging#365]
此服务在win环境，只包含两个普通的业务服务，没有使用dns,udp,ws等协议。 api每天调用的次数在100以下
![1](https://user-images.githubusercontent.com/4110405/67059647-81636100-f18c-11e9-860a-9351371d5539.jpg)

![2](https://user-images.githubusercontent.com/4110405/67059917-76f59700-f18d-11e9-8c01-ff7765aa0167.jpg)

![3](https://user-images.githubusercontent.com/4110405/67059919-79f08780-f18d-11e9-96f3-3dc987755e5f.jpg)

![4](https://user-images.githubusercontent.com/4110405/67059924-7d840e80-f18d-11e9-96a5-2b2e71979930.jpg)

**Comment by victor596** [comment]
补充图片 
![5](https://user-images.githubusercontent.com/4110405/67061747-d3f44b80-f193-11e9-9cd9-e966f74829fd.jpg)

**Comment by fanliang11** [comment]
问题出在UdpReceiveResult 和udpclient ,surging 没有出现过UdpReceiveResult ，udpclient

**Comment by victor596** [comment]
有点猜到原因了。可能是启用了dns模块然后RootDnsAddress又没有设置正确的地址所致
