### ISSUE TITLE
Kestrel记录到了奇怪的日志

### ISSUE THREAD

**Issue by victor596** [dotnetcore/surging#370]
我们只开放了http端口，但却记录到了以下日志，应该都是以我们的域名的日志才对呀

2019/11/03 14:00:50.238 INFO 171.116.45.27 Request starting HTTP/1.1 HEAD http://123.125.114.144/  
2019/11/03 14:00:50.255 INFO 171.116.45.27 Request finished in 16.6753ms 200 application/json;charset=utf-8
2019/11/03 14:00:51.405 INFO 111.224.235.93 Request starting HTTP/1.1 CONNECT http://www.voanews.com:443  
2019/11/03 14:00:51.412 INFO 111.224.235.93 Request finished in 7.2646ms 200 application/json;charset=utf-8
2019/11/03 14:00:52.268 INFO 36.32.3.16 Request starting HTTP/1.1 CONNECT http://www.baidu.com:443  
2019/11/03 14:00:52.279 INFO 36.32.3.16 Request finished in 11.0455ms 200 application/json;charset=utf-8
2019/11/03 14:00:52.475 INFO 111.162.141.105 Request starting HTTP/1.1 GET http://www.rfa.org/english/  
2019/11/03 14:00:52.475 INFO 111.162.141.105 Request finished in 10.8369ms 200 application/json;charset=utf-8
2019/11/03 14:00:54.094 INFO 119.118.5.64 Request starting HTTP/1.1 GET http://boxun.com/  
2019/11/03 14:00:54.109 INFO 119.118.5.64 Request finished in 15.1474ms 200 application/json;charset=utf-8
2019/11/03 14:00:56.377 INFO 106.45.1.109 Request starting HTTP/1.1 GET http://www.ip.cn/  
2019/11/03 14:00:56.384 INFO 106.45.1.109 Request finished in 10.8887ms 200 application/json;charset=utf-8
2019/11/03 14:00:57.431 INFO 119.118.28.34 Request starting HTTP/1.1 GET http://www.wujieliulan.com/  
2019/11/03 14:00:57.431 INFO 119.118.28.34 Request finished in 10.7553ms 200 application/json;charset=utf-8
2019/11/03 14:00:57.849 INFO 119.96.106.130 Request starting HTTP/1.1 GET http://www.epochtimes.com/  
2019/11/03 14:00:57.952 INFO 119.96.106.130 Request finished in 103.3385ms 200 application/json;charset=utf-8
2019/11/03 14:00:58.568 INFO 171.34.177.63 Request starting HTTP/1.1 CONNECT http://cn.bing.com:443  
2019/11/03 14:00:58.581 INFO 171.34.177.63 Request finished in 13.193ms 200 application/json;charset=utf-8
2019/11/03 14:01:00.174 INFO 117.14.147.37 Request starting HTTP/1.1 GET http://www.minghui.org/  
2019/11/03 14:01:00.181 INFO 117.14.147.37 Request finished in 12.2142ms 200 application/json;charset=utf-8
2019/11/03 14:01:00.181 INFO 123.157.193.233 Request starting HTTP/1.1 GET http://www.123cha.com/  
2019/11/03 14:01:00.194 INFO 123.157.193.233 Request finished in 9.7377ms 200 application/json;charset=utf-8

**Comment by CwjXFH** [comment]
Kestrel自身的日志记录功能禁用了吗？

```c#
private static void ConfigLogger(WebHostBuilderContext context, ILoggingBuilder builder)
{
    // 禁止Kestrel记录访问日志
    builder.ClearProviders();
    builder.AddFilter("Microsoft", LogLevel.None);
    builder.AddFilter("System", LogLevel.Error);
    if (context.HostingEnvironment.IsDevelopment())
    {
        builder.AddConsole();
    }
}
```

**Comment by victor596** [comment]
> Kestrel自身的日志记录功能禁用了吗？
> 
> ```cs
> private static void ConfigLogger(WebHostBuilderContext context, ILoggingBuilder builder)
> {
>     // 禁止Kestrel记录访问日志
>     builder.ClearProviders();
>     builder.AddFilter("Microsoft", LogLevel.None);
>     builder.AddFilter("System", LogLevel.Error);
>     if (context.HostingEnvironment.IsDevelopment())
>     {
>         builder.AddConsole();
>     }
> }
> ```

这是Microsoft.AspNetCore.Hosting.Internal.WebHost产生的日志。这个日志说明客户端ip通过我们去访问其它的地址。如123.157.193.233 通过surging去访问 http://www.123cha.com/,不知道是不是要关闭什么组件

**Comment by fanliang11** [comment]
首先，这个不是surging问题，surging  不会去访问那些网站。有可能产生的问题
###  代理访问
通过以上记录说明有人尝试将你的Kestrel作为代理，通过你的服务器访问他真正想要访问的网址，通过你的服务器点击一些收费广告，投票等系统，这些系统会判断是否同一个IP来防止无效的点击。你可以设置抛弃其它域名请求，或者通过防火墙设置，nginx作为代理，如果使用也需要防止出现这个问题
###  运营商DNS出现问题
如果来源IP都是某个地方的，那么可能是当地的域名解析出了问题，把很多域名都解析到你的服务器IP了

**Comment by victor596** [comment]
知道了
