### ISSUE TITLE
关于RpcContext获取不到payload的问题

### ISSUE THREAD

**Issue by chenhaiqing1985** [dotnetcore/surging#373]
通过查看其他issues我知道用RpcContext.GetContext().GetAttachment("payload")来获取payload

看到作者在网关ServicesController中用RpcContext.GetContext().SetAttachment("payload", payload);来传递payload

我调试了作者的Surging.Services.Client，当中也有RpcContext.GetContext().SetAttachment("xid",124);这样在接口中中可以接收到xid

但是我通过网关访问接口，接口中RpcContext.GetContext().GetAttachment("payload")一直是空的，调试中，网关的payload是有值的，在接口里面获取却是null

请问是我使用的问题么，是否需要在接口上配置什么？

目前一直通过继承RequestData来获取payload

**Comment by fanliang11** [comment]
![图片](https://user-images.githubusercontent.com/17928535/70535511-2f412980-1b98-11ea-88c6-215a282887de.png)
 没有任何问题，如果你还有疑问，需要远程协助，请购买企业版
