### ISSUE TITLE
rabbitmq消费失败问题

### ISSUE THREAD

**Issue by zzlProject** [dotnetcore/surging#375]
我的问题是：如果我消费失败了，怎么获取失败的消息重新处理。目前失败的消息重新放到了RabbitTestEventHanldin@Fail队列中。下面是我的代码：
[QueueConsumer("RabbitTestEventHanldin")]
    public class RabbitTestEventHanlding : BaseIntegrationEventHandler<RabbitTestEvent>
    {
        public override Task Handle(RabbitTestEvent @event)
        {
            throw new Exception("消费异常");
            var msg = Newtonsoft.Json.JsonConvert.SerializeObject(@event);
            Console.WriteLine(msg);

            return Task.CompletedTask;
        }

        public override Task Handled(EventContext context)
        {
            Console.WriteLine(nameof(Handled));
            return base.Handled(context);
        }
    }

**Comment by fanliang11** [comment]
#143

**Comment by zzlProject** [comment]
作者您好，我看了143文档。但是还是有些不明白，具体怎么写。以下是我按照自己对143的理解写的,但是好像是不对。
 [QueueConsumer("RabbitTestEventHanldin",QueueConsumerMode.Normal)]
    public class RabbitTestEventHanlding : BaseIntegrationEventHandler<RabbitTestEvent>
    {
        public override Task Handle(RabbitTestEvent @event)
        {
            throw new Exception("消费异常");
            var msg = Newtonsoft.Json.JsonConvert.SerializeObject(@event);
            Console.WriteLine(msg);

            return Task.CompletedTask;
        }


        public override Task Handled(EventContext context)
        {
            Console.WriteLine(nameof(Handled));
            return base.Handled(context);
        }
    }

    [QueueConsumer("RabbitTestEventHanldin", QueueConsumerMode.Retry)]
    public class RabbitTestRetryEventHanlding : BaseIntegrationEventHandler<RabbitTestEvent>
    {
        public override Task Handle(RabbitTestEvent @event)
        {
            var msg = Newtonsoft.Json.JsonConvert.SerializeObject(@event);
            Console.WriteLine(msg);

            return Task.CompletedTask;
        }
    }


    [QueueConsumer("RabbitTestEventHanldin", QueueConsumerMode.Fail)]
    public class RabbitTestFailEventHanlding : BaseIntegrationEventHandler<RabbitTestEvent>
    {
        public override Task Handle(RabbitTestEvent @event)
        {
            var msg = Newtonsoft.Json.JsonConvert.SerializeObject(@event);
            Console.WriteLine(msg);

            return Task.CompletedTask;
        }
    }
}

**Comment by zzlProject** [comment]
> #143

作者您好，我看了143文档。但是还是有些不明白，具体怎么写。以下是我按照自己对143的理解写的,但是好像是不对。
[QueueConsumer("RabbitTestEventHanldin",QueueConsumerMode.Normal)]
public class RabbitTestEventHanlding : BaseIntegrationEventHandler
{
public override Task Handle(RabbitTestEvent @event)
{
throw new Exception("消费异常");
var msg = Newtonsoft.Json.JsonConvert.SerializeObject(@event);
Console.WriteLine(msg);

        return Task.CompletedTask;
    }


    public override Task Handled(EventContext context)
    {
        Console.WriteLine(nameof(Handled));
        return base.Handled(context);
    }
}

[QueueConsumer("RabbitTestEventHanldin", QueueConsumerMode.Retry)]
public class RabbitTestRetryEventHanlding : BaseIntegrationEventHandler<RabbitTestEvent>
{
    public override Task Handle(RabbitTestEvent @event)
    {
        var msg = Newtonsoft.Json.JsonConvert.SerializeObject(@event);
        Console.WriteLine(msg);

        return Task.CompletedTask;
    }
}


[QueueConsumer("RabbitTestEventHanldin", QueueConsumerMode.Fail)]
public class RabbitTestFailEventHanlding : BaseIntegrationEventHandler<RabbitTestEvent>
{
    public override Task Handle(RabbitTestEvent @event)
    {
        var msg = Newtonsoft.Json.JsonConvert.SerializeObject(@event);
        Console.WriteLine(msg);

        return Task.CompletedTask;
    }
}

**Comment by fanliang11** [comment]
社区版只支持多进程独立部署Normal,Fail 队列，你可以自己修改提交PR，或者可以寻求更高级的协助

**Comment by zzlProject** [comment]
作者您好,我不太明白您的多进程独立部署Normal,Fail 队列是什么意思。您可以给我举个例子吗？不胜感激。
