### ISSUE TITLE
是不是少了个SingleInstance()

### ISSUE THREAD

**Issue by victor596** [dotnetcore/surging#378]
src\Surging.Core\Surging.Core.CPlatform\ContainerBuilderExtensions.cs  
 private static IServiceBuilder AddRuntime(this IServiceBuilder builder)
        {
            var services = builder.Services;

            services.RegisterType(typeof(ClrServiceEntryFactory)).As(typeof(IClrServiceEntryFactory)).SingleInstance();

            services.Register(provider =>
            {
                try
                {
                    var assemblys = GetReferenceAssembly();
                    var types = assemblys.SelectMany(i => i.ExportedTypes).ToArray();
                    return new AttributeServiceEntryProvider(types, provider.Resolve<IClrServiceEntryFactory>(),
                         provider.Resolve<ILogger<AttributeServiceEntryProvider>>(), provider.Resolve<CPlatformContainer>());
                }
                finally
                {
                    builder = null;
                }
            }).As<IServiceEntryProvider>();

不加SingleInstance()开销有点大.

**Comment by fanliang11** [comment]
不明白你的意思，IClrServiceEntryFactory 只是在启动的时候进行初始化，如果你问的是服务调用的返回实例的生命周期，默认是InstancePerDependency，但是实例化对象也是缓存的，如果你要返回SingleInstance，领域服务需要继承ISingleInstance接口

**Comment by victor596** [comment]
我经过调试发现每一次调用关卡都会执行 try {} finally {} 的代码,而里面的代码是扫描目录组件,觉得开销有点大

**Comment by fanliang11** [comment]
IServiceEntryProvider 不能设置为SingleInstance，因为要获取最新的ServiceEntry，如果是经常调用GetEntries， GetAllEntries，使用IServiceEntryManager接口，这个使用了SingleInstance

**Comment by victor596** [comment]
> IServiceEntryProvider 不能设置为SingleInstance，因为要获取最新的ServiceEntry，如果是经常调用GetEntries， GetAllEntries，使用IServiceEntryManager接口，这个使用了SingleInstance

知道了
