### ISSUE TITLE
下载社区版遇到的问题

### ISSUE THREAD

**Issue by zhaoguomin** [dotnetcore/surging#392]
下载的社区版，没跑起来有报错，自己研究了好久没弄明白，不知道是环境问题还是什么原因。寻思之前加入了作者的群615562965，到群里问问群友，截图在群里一问（没有at任何人), 作者(群主)出来劝说买企业版，我说先研究研究社区版，学会了才会向公司推荐购买，他说我忽悠人，试问谁会为一个不熟悉的系统花2.8万元去购买，回来慢慢研究，恐怕没几个开发人员会这么做。还说这个系统不是新人能学明白的，否则要企业版干什么！这时群里就出来一部分人，告诉你买企业版服务多么多么的好，多么的贴心！我说个人买不起。 就有人开始挖苦了，说这是炒股群，定代码有什么用（我操了，群主你不是技术出身吗，你忘本了啊！你不思把系统继续做好做强大，天天在这守株待兔等人买你的半成品。。。）。那些人还说学炒股吧，别写代码了，我说这群像骗子群。。。结果被一个管理员T出群了。。。回来想来难道被我言中了。@fanly11 你们这么整 ，这系统有几个会买。

**Comment by fanliang11** [comment]
你觉得我默认不作声有人回答你吗？你觉得又有多少人活雷锋一样去解决你的问题。别人没有义务去帮助你，然后surging 是开源的，也有博客谈了设计思路，你完全可以花时间去理解，而不是去浪费别人的时间，做什么事情都要付出，PR我很欢迎，我会审查，会优化，但是你把问题抛出，又有谁义务帮助你呢?还有针对于企业版，必然有人选择，而最大的目的是花了时间，赚了钱，还帮助了surging 忠实客户，而不是为你这位免费学习者付出时间。

**Comment by zhaoguomin** [comment]
开源可以互相学习，互相帮助。我提出问题也没有at你，我也没刷屏，如果谁遇到同样问题的就帮助解答下，没有就拉倒。 我不信你开发这套系统没有向别人请教过问题。你要说你这群615562965只为付费用户解答问题，你就别允许非付费用户加入，你开源别人就会学习这个系统，遇到问题在群里请教问题，这不正常吗，你们不帮也没关系，不该冷嘲热讽的。不熟悉你的系统当然要学习研究，不可能上来就付费，我说学好了自然会向别人推荐。你怎么说的，说我骗人，就是为了让你帮解决问题。你这心理我也是服了。你首先是把人往坏处想，首先选择的是不相信别人。我不知道你这个系统开发到现在度，有没有得到别人的帮助，如果帮助你的人之初都选择不相信你，你的系统还会走到今天吗？

**Comment by fanliang11** [comment]
你觉得怎么样是帮助呢？开源是不是帮助，作为代码是程序员沟通的桥梁，本人已经把思想融入到代码里，你花时间肯定能有所收获，如果你不想花时间，只想请个私教，手把手教，那么请你付费。我也指望你推荐，只要你不说我骗子就可以了。如果你觉得我做的不妥，那么你可以说的不妥，可以离开。

**Comment by fanliang11** [comment]
你觉得怎么样是帮助呢？开源是不是帮助，作为代码是程序员沟通的桥梁，本人已经把思想融入到代码里，你花时间肯定能有所收获，如果你不想花时间，只想请个私教，手把手教，那么请你付费。我也不指望你推荐，只要你不说我骗子就可以了。如果你觉得我做的不妥，或者说的不妥，可以离开。

**Comment by zhaoguomin** [comment]
我又没指定找你解决问题，我看过你博客上说的话，的确有些人用着你的东西，还感觉你欠他们似的，提出无理的要求占用你的精力。我不付费，我也不会要求你解决问题，但是我觉得学习任何一个系统，不可能没有交流，起码初学者之间可以做到互相帮助，否则都闷头搞自己的，那就不会有开源这种事。我说骗子，是你群里那些人，你自己不是没看到，他们所说与你无益， 本来挺好的东西，让他们这么一整，感觉就像是忽悠人不是吗？

**Comment by fanliang11** [comment]
你认为在我的群里就能得到答案吗?不能! 两年来 不论是QQ群还是issues 都是我一个人解决的。每个作者都有权力去制定规则运营自己开源项目，而不是像你一样没有得到帮助，来社区胡闹，你觉得这样有效果吗？识货者依然选择，看笑话者只会引来谈资。

**Comment by zhaoguomin** [comment]
至于你说不用我推荐这话，我觉得是否向别人或公司推荐surging这个系统，取决于这个系统是否能为对方解决问题，是否有给用户带来好处， 如果好用能解决问题自然会推荐，反之就不会推荐。

**Comment by zhaoguomin** [comment]
如你所说，如果在群里得不到答案，没问题，帮是人情，不帮是本分。但你说我胡闹，我不同意你的说法，我并非没有得到帮助而来这发贴，而是你群里那些人的态度，对新手的态度，还忽悠别人炒股，不像骗子吗，允放他们胡说八道，不允许我说他们是骗子吗，说了就T出群，呵呵，允放他们放火，不允许我点灯。

**Comment by tonyqus** [comment]
作者说的没错，你就是胡闹。Github issue是用来提问题的，不是用来发泄情绪的。@zhaogunmin
