### ISSUE TITLE
使用api网关遇到的问题

### ISSUE THREAD

**Issue by billyang** [dotnetcore/surging#49]
hi~
我在使用api网关时，遇到几点小问题
1. ModuleName 是不是取Service前的Name；比如**UserAppService**,  ModuleName 是UserApp , 取User 不行

2. 使用api网关能否指定http Method, GET/ POST ;  貌似现在只能是 POST JSON

**Comment by fanliang11** [comment]
@billyang  
1.在一个接口多个实例下就要设置ModuleName ，以标识实例名，比如过渡升级功能，新旧版本功能会同时部署，这时候你可以通过版本号来设置ModuleName ，再比如支付功能接口，需要实现多个支付方式。
另一种情况是一个接口对应一个实例，这不需要设置ModuleName ，在调用网关的时候serviceKey不用传
2.因为提交的参数设置了FromBody，所以调用有参数的接口方法时候，不支持GET,只支持put,post,delete
无参数的情况可以使用GET

**Comment by billyang** [comment]
好的，谢谢。
插播个无关紧要的小问题，shortcut icon 指定的是 Eworkpal.ico，ApiGateway项目没有这个文件。应该是favicon.ico

这是我的项目框架图，正在努力surging学习。希望surging越来越好
![image](https://user-images.githubusercontent.com/1887935/35420544-09a8651a-0279-11e8-9e88-73aa7e6f4669.png)

**Comment by fanliang11** [comment]
这是我以前公司的项目，为了节约时间，我引用过来改了界面，我会把原来的ico删除,surging都是以前的积累，还有很多干货没用上来
