### ISSUE TITLE
为什么我这个提示未注册，但是另外一个又是正常的，一样的写法

### ISSUE THREAD

**Issue by zhouchina** [dotnetcore/surging#59]
![image](https://user-images.githubusercontent.com/37869578/38030602-a22bb3fa-32cb-11e8-99da-115d6825b203.png)
写法是一样的   引用也是一样的，需要在哪里重新注册吗

**Comment by fanliang11** [comment]
请查看是否按照规则注册，或者是查看Service 和Repository构造函数是否有其它第三方组件未注册的情况
 请参照文档进行配置[文档](https://github.com/dotnetcore/surging/blob/master/docs/docs.en/INDEX.md)

**Comment by zhouchina** [comment]
这个问题已经解决了，现在是数据库的数据查询到了 ，在web里调服务的时候返回的为null
![image](https://user-images.githubusercontent.com/37869578/38074684-2955ae4e-3362-11e8-8003-444a89397e07.png)
![image](https://user-images.githubusercontent.com/37869578/38074698-33ab0894-3362-11e8-9c7c-d361543af958.png)
![image](https://user-images.githubusercontent.com/37869578/38074714-3ff11fc6-3362-11e8-99b7-42f96cf440af.png)

在web 里的 Action 接受的list始终为null， 在服务实现里是有返回的

**Comment by fanliang11** [comment]
请问使用的是什么编码，如果是MessagePackCodec编码，请注意使用常用的类型List
或者你非要使用IList,那么请使用JsonCodec编码

**Comment by fanliang11** [comment]
但是我刚刚测试未出现问题，请具体描述你的问题
我的测试项目
![4](https://user-images.githubusercontent.com/17928535/38075628-963b23ec-3365-11e8-8229-2b6942f4735a.png)
具体可以查看[DEMO](https://github.com/billyang/SurgingDemo/blob/master/src/Bill.Demo.Solutions/Bill.Demo.ModuleServices/Users/UserService.cs)

**Comment by zhouchina** [comment]
好的  我再检查检查

**Comment by fanliang11** [comment]
猜测应该是远程服务调用发生错误，熔断返回null。
MessagePackCodec编码支持IList,  Demo 没有出现问题
![6](https://user-images.githubusercontent.com/17928535/38076215-8ae75388-3367-11e8-8d02-1d688cec6d0a.png)

**Comment by zhouchina** [comment]
不知道什么情况  不管我怎么清理解决方案 重新生成  返回的List 始终为 null  但是传string 类型的 返回 都可以接收到

**Comment by fanliang11** [comment]
client 和server 统一使用的是MessagePackCodec编码吗

**Comment by fanliang11** [comment]
或者你的模型可以贴出来吗？里面是否有enum类型

**Comment by zhouchina** [comment]
![image](https://user-images.githubusercontent.com/37869578/38076485-55ad7e26-3368-11e8-8bed-8d016526cb14.png)
这个是模型
![image](https://user-images.githubusercontent.com/37869578/38076509-648a17ec-3368-11e8-8cf4-22a33dce7324.png)
web 里面 跟billyang 的demo 一样的

**Comment by fanliang11** [comment]
Web 和 Server 是否统一使用了   option.UseMessagePackCodec();配置

**Comment by zhouchina** [comment]
![image](https://user-images.githubusercontent.com/37869578/38076726-14c4c0bc-3369-11e8-8b6f-e5556362d6af.png)
这个是web 里的Startup
![image](https://user-images.githubusercontent.com/37869578/38076780-3b7f87aa-3369-11e8-8942-ab3292ca5282.png)
这个是Server 里的Program

**Comment by zhouchina** [comment]
没有啊  也没提示 也不报错  就是返回的为null   在服务实现方法里又能查到数据

**Comment by fanliang11** [comment]
返回null 是因为发生错误或者调式的时候超时，从而产生熔断。没有日志，那我就不相信了
